[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
lazy_static = "1.4.0"
regex = "1.7.0"
serde = { version = "1.0.147", features = ["derive"] }
uuid = { version = "1.2.1", features = ["v4", "fast-rng"] }
