[package]
name = "auth-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
bcrypt = "0.13.0"
enum_dispatch = "0.3.8"
kernel = { version = "0.1.0", path = "../kernel" }
lazy_static = "1.4.0"
mockall = "0.11.3"
serde = { version = "1.0.147", features = ["derive"] }
tokio = { version = "1.21.2", features = ["rt", "macros"] }
